###
GET http://localhost:3001/api/persons/

###
DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Mitchell Tang",
    "number": "1-925-317-2085"
}